services:
  db:
    image: postgres:17.4-alpine3.21 
    container_name: slack-sentiment-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sentiment_data
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d sentiment_data"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: slack-sentiment-dashboard
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: slack-sentiment-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db: